GET https://ancient-atoll-18219.herokuapp.com/api/persons

###
GET https://ancient-atoll-18219.herokuapp.com/info

###
GET https://ancient-atoll-18219.herokuapp.com/api/persons/1

###
DELETE https://ancient-atoll-18219.herokuapp.com/api/persons/1

###
POST https://ancient-atoll-18219.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "sample",
    "number": "1234-1234-34"
}

###
POST https://ancient-atoll-18219.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}