GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/1

###
DELETE http://localhost:3001/api/persons/5

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "sample",
    "number": "1234-1234-34"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Arto Hellas",
    "number": "040-123456"
}